export { API_BASE_URL, UPLOADS_BASE_URL as UPLOADS_URL, SOCKET_URL } from '../config';

export const ENDPOINTS = {
  registerUser: '/auth/register/user',
  loginUser: '/auth/login/user',
  products: '/products',
  productSearch: '/products/search',
  productSuggest: '/products/suggest',
  complaints: '/complaints',
  productDetail: (id) => `/products/${id}`,
  productFrequentlyBought: (id) => `/products/${id}/frequently-bought-with`,
  productReviews: (id) => `/products/${id}/reviews`,
  productReviewStats: (id) => `/products/${id}/review-stats`,
  productSimilar: (id) => `/products/${id}/similar`,
  productVariants: (id) => `/products/${id}/variants`,
  productView: (id) => `/products/${id}/view`,
  productNotifyStock: (id) => `/products/${id}/notify-stock`,
  productFlashSale: (id) => `/products/${id}/flash-sale`,
  stories: '/stories',
  storyView: (id) => `/stories/${id}/view`,
  companyStories: (id) => `/companies/${id}/stories`,
  recentlyViewed: (phone) => `/users/${phone}/recently-viewed`,
  recommendations: (phone) => `/users/${phone}/recommendations`,
  companies: '/companies',
  companyDetail: (id) => `/companies/${id}`,
  nearestCompanies: '/companies/nearest',
  cart: (phone) => `/cart/${phone}`,
  cartCount: (phone) => `/cart/${phone}/count`,
  cartAdd: '/cart',
  cartSet: '/cart/set',
  cartDeleteItem: (id) => `/cart/item/${id}`,
  cartClear: (phone) => `/cart/user/${phone}`,
  favorites: (phone) => `/favorites/${phone}`,
  favoritesCount: (phone) => `/favorites/${phone}/count`,
  favoritesToggle: '/favorites/toggle',
  favoritesCheck: '/favorites/check',
  orders: '/orders',
  orderDetail: (id) => `/orders/${id}`,
  orderStatus: (id) => `/orders/${id}/status`,
  orderCourierLocation: (id) => `/orders/${id}/courier-location`,
  userProfile: (phone) => `/users/${phone}/profile`,
  userAvatar: (phone) => `/users/${phone}/avatar`,
  userDefaultAddress: (phone) => `/users/${phone}/default-delivery-address`,
  categories: '/categories',
  categoryProducts: '/categories/products',
  notifications: '/notifications',
  notificationsUnread: '/notifications/unread-count',
  notificationRead: (id) => `/notifications/${id}/read`,
  notificationsMarkAll: '/notifications/mark-all-read',
  pushToken: '/notifications/push-token',
  approvedDiscounts: '/discounts/approved',
  approvedAggressiveDiscounts: '/aggressive-discounts/approved',
  ads: '/ads',
  reviews: '/reviews',
  reviewUploadImage: '/reviews/upload-image',
  reviewVote: (id) => `/reviews/${id}/vote`,
  paymentCards: (phone) => `/payment-cards/${phone}`,
  paymentCardsAdd: '/payment-cards',
  paymentCardDelete: (id) => `/payment-cards/${id}`,
  paymentCardDefault: (id) => `/payment-cards/${id}/default`,
  companySubscribe: (id) => `/companies/${id}/subscribe`,
  companyUnsubscribe: (id) => `/companies/${id}/unsubscribe`,
  companyStats: (id) => `/companies/${id}/stats`,
  userFrequentLocations: (phone) => `/users/${phone}/frequent-locations`,
  userAddresses: (phone) => `/users/${phone}/addresses`,
  userAddressDetail: (phone, id) => `/users/${phone}/addresses/${id}`,
  userAddressDefault: (phone, id) => `/users/${phone}/addresses/${id}/default`,
  // ❓ Вопросы к товару и ↩️ возвраты
  productQuestions: (id) => `/products/${id}/questions`,
  returns: '/returns',
  // ⭐ Кэшбэк-баллы (лояльность)
  loyalty: (phone) => `/loyalty/${phone}`,
  loyaltyRedeem: '/loyalty/redeem',
  // 🎟️ Промокоды
  promoValidate: '/promo-codes/validate',
  promoRedeem: '/promo-codes/redeem',
  // 🎉 Скидочные кампании
  campaigns: '/campaigns',
  // 🗺️ Зоны доставки, нарисованные админом
  regions: '/regions',
  regionsResolve: '/regions/resolve',
  // 📜 Политика конфиденциальности
  policy: (audience) => `/policies/${audience}`,
  policyAccept: (audience) => `/policies/${audience}/accept`,
};
